# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       docker build -t eu.gcr.io/$PROJECT_ID/refrstore:$BUILD_ID .

# # - name: 'eu.gcr.io/$PROJECT_ID/refrstore:$BUILD_ID'
# #   entrypoint: 'sh'
# #   args:
# #   - '-c'
# #   - |
# #     yarn audit || true
# # - name: 'aquasec/trivy'
# #   args: ['image', 'eu.gcr.io/$PROJECT_ID/refrstore:$BUILD_ID']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'eu.gcr.io/$PROJECT_ID/refrstore:$BUILD_ID']
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'selcorstore', '--image', 'eu.gcr.io/$PROJECT_ID/refrstore:$BUILD_ID', '--region', 'europe-north1']

# images:
# - 'eu.gcr.io/$PROJECT_ID/refrstore:$BUILD_ID'

# timeout: 800s

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$IMAGE', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$IMAGE']
  
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'selcorstore, '--image', 'gcr.io/$PROJECT_ID/$IMAGE', '--region', 'europe-north1']

images:
- gcr.io/$PROJECT_ID/$IMAGE