version: 2.1
jobs:
 test:
   working_directory: ~/refrstore
   docker:
     - image: cimg/python:3.10.6
   steps:
     - checkout
     - run:
         command: python --version
     - run:
         command: pip install -r requirements.txt
     - run:
         command: ./refrstore/manage.py test
 deploy-aws:
   working_directory: ~/refrstore
   docker:
     - image: cimg/python:3.10.6
   steps:
     - checkout
     - run:
         name: Installing deployment dependencies
         working_directory: ~/refrstore
         command: pip install awsebcli --upgrade
     - run:
         name: Deploying application to Elastic Beanstalk
         command: eb deploy

         
workflows:
 version: 2.1
 build-test-and-deploy:
   jobs:
     - test
     - deploy-aws:
         requires:
           - test
         filters:
            branches:
              only:
                - master
