version: 2.1


orbs:
  # rollbar: rollbar/deploy@1.0.1
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
 test:
   working_directory: ~/refrstore
   docker:
     - image: cimg/python:3.10.6
   steps:
     - checkout
     - run:
         command: python --version
     - run:
         command: pip install -r requirements.txt
     - run:
         command: ./manage.py test
 deploy-gcp:
   working_directory: ~/refrstore
   executor: gcp-cli/default
   parameters:
      google-project-id:
        type: env_var_name
        default: GOOGLE_PROJECT_ID
      gcloud-service-key:
        type: env_var_name
        default: GCLOUD_SERVICE_KEY
   steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize:
          google-project-id: << parameters.google-project-id >>
          gcloud-service-key: << parameters.gcloud-service-key >>
      - run:
          name: Deploy to Cloud Build Production
          command: |
            gcloud builds submit --async --config=cloudbuild.yaml .

         
workflows:
 version: 2.1
 build-test-and-deploy:
   jobs:
     - test
     - deploy-gcp:
         requires:
           - test
         filters:
            branches:
              only:
                - GCP-Deployment
